version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    logging:
      driver: json-file
    expose:
      - 8000

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    logging:
      driver: json-file
    expose:
      - 3000
    tty: true

  nginx:
    image: nginx:1.13.7
    logging:
      driver: json-file
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - backend
      - frontend
    links:
      - backend
      - frontend
